export const REQUEST: string = 'REQUEST';
export const USER_SUCCESS: string = 'USER_SUCCESS';
export const USER_FAILED: string = 'USER_FAILED';

// products
export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_ERROR = 'PRODUCT_LIST_ERROR';
export const PRODUCT_LIST_REMOVE_SUCCESS = 'PRODUCT_LIST_REMOVE_SUCCESS';

//  cart
export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_DELETE_ITEM = 'CART_DELETE_ITEM';
export const CART_CLEAR_ITEM = 'CART_CLEAR_ITEM';

//address
export const SAVE_ADDRESS = 'SAVE_ADDRESS';

// order GROUP
export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_ERROR = 'ORDER_LIST_ERROR';

// order SINGLE
export const ORDER_SINGLE_REQUEST = 'ORDER_SINGLE_REQUEST';
export const ORDER_LIST_DELETE_SUCCESS = 'ORDER_LIST_DELETE_SUCCESS';
export const ORDER_LIST_CREATE_SUCCESS = 'ORDER_LIST_CREATE_SUCCESS';
export const ORDER_SINGLE_SUCCESS = 'ORDER_SINGLE_SUCCESS';
export const ORDER_SINGLE_ERROR = 'ORDER_SINGLE_ERROR';
